---
version: '3'
services:
  zoo1:
    image: zookeeper:3.4
    restart: always
    hostname: zoo1
    ports:
      - "127.0.0.1:2181:2181"
    volumes:
      - zoo1_data:/data
      - zoo1_datalog:/datalog
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888

  zoo2:
    image: zookeeper:3.4
    restart: always
    hostname: zoo2
    ports:
      - "127.0.0.1:2182:2181"
    volumes:
      - zoo2_data:/data
      - zoo2_datalog:/datalog
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=0.0.0.0:2888:3888 server.3=zoo3:2888:3888

  zoo3:
    image: zookeeper:3.4
    restart: always
    hostname: zoo3
    ports:
      - "127.0.0.1:2183:2181"
    volumes:
      - zoo3_data:/data
      - zoo3_datalog:/datalog
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=0.0.0.0:2888:3888

  broker1:
    build: 
      context: ./kafka
      args:
        KAFKA_VERSION: 2.2.0
    image: kafka:2.2.0
    hostname: broker1
    ports:
      - "127.0.0.1:9093:9093"
    depends_on:
      - "zoo1"
      - "zoo2"
      - "zoo3"
    volumes:
      - broker1:/var/lib/kafka/kafka-logs
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZK_CONNECT: zoo1:2181,zoo2:2182,zoo3:2183
      KAFKA_LISTENERS: INTERNAL://broker1:9092,EXTERNAL://:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://broker1:9092,EXTERNAL://127.0.0.1:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL

  broker2:
    build: 
      context: ./kafka
      args:
        KAFKA_VERSION: 2.2.0
    image: kafka:2.2.0
    hostname: broker2
    ports:
      - "127.0.0.1:9094:9094"
      - "127.0.0.1:29999:29999"
    depends_on:
      - "zoo1"
      - "zoo2"
      - "zoo3"
    volumes:
      - broker2:/var/lib/kafka/kafka-logs
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZK_CONNECT: zoo1:2181,zoo2:2182,zoo3:2183
      KAFKA_LISTENERS: INTERNAL://broker2:9092,EXTERNAL://:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://broker2:9092,EXTERNAL://127.0.0.1:9094
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      JMX_PORT: 29999

volumes:
  zoo1_data:
  zoo1_datalog:
  zoo2_data:
  zoo2_datalog:
  zoo3_data:
  zoo3_datalog:
  broker1:
  broker2:
