---
version: '3'
services:
  zoo1:
    image: zookeeper:3.4
    restart: always
    hostname: zoo1
    ports:
      - "127.0.0.1:2181:2181"
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888

  zoo2:
    image: zookeeper:3.4
    restart: always
    hostname: zoo2
    ports:
      - "127.0.0.1:2182:2181"
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=0.0.0.0:2888:3888 server.3=zoo3:2888:3888

  zoo3:
    image: zookeeper:3.4
    restart: always
    hostname: zoo3
    ports:
      - "127.0.0.1:2183:2181"
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=0.0.0.0:2888:3888

  broker1:
    build: 
      context: ./kafka
      args:
        KAFKA_VERSION: 2.2.0
    image: kafka:2.2.0
    hostname: broker1
    ports:
      - "127.0.0.1:9092:9092"
    depends_on:
      - "zoo1"
      - "zoo2"
      - "zoo3"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZK_CONNECT: zoo1:2181,zoo2:2182,zoo3:2183
