---
version: '3.4'
services:
  zoo1:
    image: zookeeper:3.4
    restart: always
    hostname: zoo1
    ports:
      - "127.0.0.1:2181:2181"
    volumes:
      - zoo1_data:/data
      - zoo1_datalog:/datalog
    environment:
      - ZOO_TICK_TIME=${ZOO_TICK_TIME:-2000}
      - ZOO_INIT_LIMIT=${ZOO_INIT_LIMIT:-5}
      - ZOO_SYNC_LIMIT=${ZOO_SYNC_LIMIT:-2}
      - ZOO_MAX_CLIENT_CNXNS=${ZOO_MAX_CLIENT_CNXNS:-60}
      - ZOO_ADMINSERVER_ENABLED=${ZOO_ADMINSERVER_ENABLED:-true}
      - ZOO_MY_ID=1
      - ZOO_SERVERS=server.1=0.0.0.0:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888
    healthcheck:
      test: nc -z localhost 2181 || exit -1
      start_period: 20s
      interval: 5s
      timeout: 10s
      retries: 10

  zoo2:
    image: zookeeper:3.4
    restart: always
    hostname: zoo2
    ports:
      - "127.0.0.1:2182:2181"
    volumes:
      - zoo2_data:/data
      - zoo2_datalog:/datalog
    environment:
      - ZOO_TICK_TIME=${ZOO_TICK_TIME:-2000}
      - ZOO_INIT_LIMIT=${ZOO_INIT_LIMIT:-5}
      - ZOO_SYNC_LIMIT=${ZOO_SYNC_LIMIT:-2}
      - ZOO_MAX_CLIENT_CNXNS=${ZOO_MAX_CLIENT_CNXNS:-60}
      - ZOO_ADMINSERVER_ENABLED=${ZOO_ADMINSERVER_ENABLED:-true}
      - ZOO_MY_ID=2
      - ZOO_SERVERS=server.1=zoo1:2888:3888 server.2=0.0.0.0:2888:3888 server.3=zoo3:2888:3888
    healthcheck:
      test: nc -z localhost 2181 || exit -1
      start_period: 20s
      interval: 5s
      timeout: 10s
      retries: 10

  zoo3:
    image: zookeeper:3.4
    restart: always
    hostname: zoo3
    ports:
      - "127.0.0.1:2183:2181"
    volumes:
      - zoo3_data:/data
      - zoo3_datalog:/datalog
    environment:
      - ZOO_TICK_TIME=${ZOO_TICK_TIME:-2000}
      - ZOO_INIT_LIMIT=${ZOO_INIT_LIMIT:-5}
      - ZOO_SYNC_LIMIT=${ZOO_SYNC_LIMIT:-2}
      - ZOO_MAX_CLIENT_CNXNS=${ZOO_MAX_CLIENT_CNXNS:-60}
      - ZOO_ADMINSERVER_ENABLED=${ZOO_ADMINSERVER_ENABLED:-true}
      - ZOO_MY_ID=3
      - ZOO_SERVERS=server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888
    healthcheck:
      test: nc -z localhost 2181 || exit -1
      start_period: 20s
      interval: 5s
      timeout: 10s
      retries: 10

  zoonavigator:
    image: "elkozmon/zoonavigator:${ZOONAVIGATOR_VERSION:-1.1.2}"
    restart: always
    hostname: zoonavigator
    ports:
      - "127.0.0.1:9000:9000"
    environment:
      - HTTP_PORT:9000

  broker1:
    build: 
      context: ./kafka
      args:
        KAFKA_VERSION: ${KAFKA_VERSION:-3.3.2}
    image: "kafka:${KAFKA_VERSION:-3.3.2}"
    hostname: broker1
    ports:
      - "127.0.0.1:9093:9093"
    depends_on:
      zoo1:
        condition: service_healthy
      zoo2:
        condition: service_healthy
      zoo3:
        condition: service_healthy
    volumes:
      - broker1:/var/lib/kafka/kafka-logs
      - ./certs/keystores:/usr/local/kafka/keystores
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZK_CONNECT=zoo1:2181,zoo2:2182,zoo3:2183
      - KAFKA_LISTENERS=INTERNAL://broker1:9092,EXTERNAL://:9093
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=${KAFKA_LISTENER_SECURITY_PROTOCOL_MAP:-INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT}
      - KAFKA_ADVERTISED_LISTENERS=INTERNAL://broker1:9092,EXTERNAL://127.0.0.1:9093
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_SSL_TRUSTSTORE_LOCATION
      - KAFKA_SSL_TRUSTSTORE_PASSWORD
      - KAFKA_SSL_KEYSTORE_LOCATION=${KAFKA_SSL_KEYSTORE_LOCATION}/broker1.keystore.jks
      - KAFKA_SSL_KEYSTORE_PASSWORD
      - KAFKA_SSL_CLIENT_AUTH
      - KAFKA_DEFAULT_REPLICATION_FACTOR

  broker2:
    build: 
      context: ./kafka
      args:
        KAFKA_VERSION: ${KAFKA_VERSION:-3.3.2}
    image: "kafka:${KAFKA_VERSION:-3.3.2}"
    hostname: broker2
    ports:
      - "127.0.0.1:9094:9094"
      - "127.0.0.1:29999:29999"
    depends_on:
      zoo1:
        condition: service_healthy
      zoo2:
        condition: service_healthy
      zoo3:
        condition: service_healthy
    volumes:
      - broker2:/var/lib/kafka/kafka-logs
      - ./certs/keystores:/usr/local/kafka/keystores
    environment:
      - KAFKA_BROKER_ID=2
      - KAFKA_ZK_CONNECT=zoo1:2181,zoo2:2182,zoo3:2183
      - KAFKA_LISTENERS=INTERNAL://broker2:9092,EXTERNAL://:9094
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=${KAFKA_LISTENER_SECURITY_PROTOCOL_MAP:-INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT}
      - KAFKA_ADVERTISED_LISTENERS=INTERNAL://broker2:9092,EXTERNAL://127.0.0.1:9094
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_SSL_TRUSTSTORE_LOCATION
      - KAFKA_SSL_TRUSTSTORE_PASSWORD
      - KAFKA_SSL_KEYSTORE_LOCATION=${KAFKA_SSL_KEYSTORE_LOCATION}/broker2.keystore.jks
      - KAFKA_SSL_KEYSTORE_PASSWORD
      - KAFKA_SSL_CLIENT_AUTH
      - KAFKA_DEFAULT_REPLICATION_FACTOR
      - JMX_PORT=29999

volumes:
  zoo1_data:
  zoo1_datalog:
  zoo2_data:
  zoo2_datalog:
  zoo3_data:
  zoo3_datalog:
  broker1:
  broker2:
